---
- name: COMMON install python interface required by Ansible DNF module
  raw: dnf install -yq python2-dnf
  changed_when: False

- name: COMMON install extra dependencies required by the development system
  dnf: name={{ item }} state=present
  with_items:
      - gcc
      - kernel-devel
      - kernel-headers
      - readline-devel
      - zlib-devel
      - subversion
      - python-devel
      - python-psycopg2
      - libselinux-python
      - redhat-rpm-config
      - libpqxx
      - httpd
      - phpPgAdmin
      - meld
      - uudeview

- name: COMMON ensure .ssh directory exists
  file:
    dest: "{{ user_home }}/.ssh/"
    mode: 0700
    owner: "{{ user_account }}"
    group: "{{ user_account }}"
    state: directory

- name: COMMON copy private key
  copy:
    content: "{{ private_key }}"
    dest: "{{ user_home }}/.ssh/id_rsa"
    mode: 0600
    owner: "{{ user_account }}"
    group: "{{ user_account }}"

- name: COMMON copy public key
  copy:
    content: "{{ public_key }}"
    dest: "{{ user_home }}/.ssh/id_rsa.pub"
    mode: 0644
    owner: "{{ user_account }}"
    group: "{{ user_account }}"

- name: COMMON copy ssh client config file
  copy:
    src: files/config/ssh_config
    dest: "{{ user_home }}/.ssh/config"
    owner: "{{ user_account }}"
    group: "{{ user_account }}"
    mode: 0600

- name: COMMON ensure httpd service is started and enabled
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: COMMON ensure phpPgAdmin configuraion is listening to localhost
  lineinfile:
    state: present
    path: "/etc/phpPgAdmin/config.inc.php"
    regexp: "^.*\\$conf\\['servers'\\]\\[0\\]\\['host'\\].*$"
    line: "\t$conf['servers'][0]['host'] = 'localhost';"
    backrefs: yes

- name: COMMON ensure phpMyAdmin can be accessed from all hosts
  lineinfile:
    state: present
    path: "/etc/httpd/conf.d/phpPgAdmin.conf"
    regexp: "^.*Require local.*$"
    line: "\tRequire all granted"
    backrefs: yes
  notify: reload httpd

- name: COMMON disable SELinux
  selinux: state=disabled

- name: COMMON change hostname
  hostname: name=dev

- name: COMMON disable firewall
  systemd:
    name: firewalld
    state: stopped
    enabled: no
