ns_section ns/MimeTypes
ns_param Default application/octet-stream
ns_param NoExtension text/plain
ns_param .pcd image/x-photo-cd
ns_param .prc application/x-pilot
ns_param .mp3 sound/mp3
ns_param .css text/css
ns_param .doc application/msword
ns_param .rtf application/rtf
ns_param .xls application/msexcel
ns_param .xlc application/msexcel
ns_param .fm4 application/x-framemaker
ns_param .fm5 application/x-framemaker
ns_param .ppt application/vnd.ms-powerpoint
ns_param .pot application/vnd.ms-powerpoint
ns_param .pps application/vnd.ms-powerpoint
ns_param .mpp application/vnd.ms-project
ns_param .dvi application/x-dvi
ns_param .mpg application/x-mplayer2
ns_param .asf video/x-ms-asf
ns_param .wmv video/x-ms-wmv
ns_param .bin application/octet-stream
ns_param .dms application/octet-stream
ns_param .lha application/octet-stream
ns_param .lzh application/octet-stream
ns_param .exe application/octet-stream
ns_param .class application/octet-stream
ns_param .so application/octet-stream
ns_param .dll application/octet-stream
ns_param .sxw application/vnd.sun.xml.writer
ns_param .stw application/vnd.sun.xml.writer.template
ns_param .sxg application/vnd.sun.xml.writer.global
ns_param .sdw application/vnd.stardivision.writer
ns_param .sgl application/vnd.stardivision.writer-global
ns_param .sxc application/vnd.sun.xml.calc
ns_param .stc application/vnd.sun.xml.calc.template
ns_param .sdc application/vnd.stardivision.calc
ns_param .sxi application/vnd.sun.xml.impress
ns_param .sti application/vnd.sun.xml.impress.template
ns_param .sdd application/vnd.stardivision.impress
ns_param .sxd application/vnd.sun.xml.draw
ns_param .std application/vnd.sun.xml.draw.template
ns_param .sda application/vnd.stardivision.draw
ns_param .sxm application/vnd.sun.xml.math
ns_param .smf application/vnd.stardivision.math
ns_param .sxw application/vnd.sun.xml.writer
ns_param .stw application/vnd.sun.xml.writer.template
ns_param .sxg application/vnd.sun.xml.writer.global
ns_param .sdw application/vnd.stardivision.writer
ns_param .sgl application/vnd.stardivision.writer-global
ns_param .sxc application/vnd.sun.xml.calc
ns_param .stc application/vnd.sun.xml.calc.template
ns_param .sdc application/vnd.stardivision.calc
ns_param .sxi application/vnd.sun.xml.impress
ns_param .sti application/vnd.sun.xml.impress.template
ns_param .sdd application/vnd.stardivision.impress
ns_param .sxd application/vnd.sun.xml.draw
ns_param .std application/vnd.sun.xml.draw.template
ns_param .sda application/vnd.stardivision.draw
ns_param .sxm application/vnd.sun.xml.math
ns_param .smf application/vnd.stardivision.math
ns_param .sxw application/vnd.sun.xml.writer
ns_param .stw application/vnd.sun.xml.writer.template
ns_param .sxg application/vnd.sun.xml.writer.global
ns_param .sdw application/vnd.stardivision.writer
ns_param .sgl application/vnd.stardivision.writer-global
ns_param .sxc application/vnd.sun.xml.calc
ns_param .stc application/vnd.sun.xml.calc.template
ns_param .sdc application/vnd.stardivision.calc
ns_param .sxi application/vnd.sun.xml.impress
ns_param .sti application/vnd.sun.xml.impress.template
ns_param .sdd application/vnd.stardivision.impress
ns_param .sxd application/vnd.sun.xml.draw
ns_param .std application/vnd.sun.xml.draw.template
ns_param .sda application/vnd.stardivision.draw
ns_param .sxm application/vnd.sun.xml.math
ns_param .smf application/vnd.stardivision.math
ns_param .odt application/vnd.oasis.opendocument.text
ns_param .ott application/vnd.oasis.opendocument.text-template
ns_param .ods application/vnd.oasis.opendocument.spreadsheet
ns_param .ots application/vnd.oasis.opendocument.spreadsheet-template
ns_param .odp application/vnd.oasis.opendocument.presentation
ns_param .otp application/vnd.oasis.opendocument.presentation-template
ns_param .pdf application/pdf
ns_param .ez application/andrew-inset
ns_param .hqx application/mac-binhex40
ns_param .cpt application/mac-compactpro
ns_param .doc application/msword
ns_param .bin application/octet-stream
ns_param .oda application/oda
ns_param .ai application/postscript
ns_param .rtf application/rtf
ns_param .smi application/smil
ns_param .mif application/vnd.mif
ns_param .xls application/vnd.ms-excel
ns_param .ppt application/vnd.ms-powerpoint
ns_param .sic application/vnd.wap.sic
ns_param .slc application/vnd.wap.slc
ns_param .wbxml application/vnd.wap.wbxml
ns_param .wmlc application/vnd.wap.wmlc
ns_param .wmlsc application/vnd.wap.wmlscriptc
ns_param .bcpio application/x-bcpio
ns_param .bz2 application/x-bzip2
ns_param .vcd application/x-cdlink
ns_param .pgn application/x-chess-pgn
ns_param .cpio application/x-cpio
ns_param .csh application/x-csh
ns_param .dcr application/x-director
ns_param .dvi application/x-dvi
ns_param .spl application/x-futuresplash
ns_param .gtar application/x-gtar
ns_param .gz application/x-gzip
ns_param .hdf application/x-hdf
ns_param .js application/x-javascript
ns_param .kwd application/x-kword
ns_param .ksp application/x-kspread
ns_param .kpr application/x-kpresenter
ns_param .chrt application/x-kchart
ns_param .kil application/x-killustrator
ns_param .skp application/x-koan
ns_param .latex application/x-latex
ns_param .nc application/x-netcdf
ns_param .rpm application/x-rpm
ns_param .sh application/x-sh
ns_param .shar application/x-shar
ns_param .swf application/x-shockwave-flash
ns_param .sit application/x-stuffit
ns_param .sv4cpio application/x-sv4cpio
ns_param .sv4crc application/x-sv4crc
ns_param .tar application/x-tar
ns_param .tcl application/x-tcl
ns_param .tex application/x-tex
ns_param .texinfo application/x-texinfo
ns_param .t application/x-troff
ns_param .man application/x-troff-man
ns_param .me application/x-troff-me
ns_param .ms application/x-troff-ms
ns_param .ustar application/x-ustar
ns_param .src application/x-wais-source
ns_param .zip application/zip
ns_param .au audio/basic
ns_param .mid audio/midi
ns_param .mpga audio/mpeg
ns_param .aif audio/x-aiff
ns_param .m3u audio/x-mpegurl
ns_param .ram audio/x-pn-realaudio
ns_param .ra audio/x-realaudio
ns_param .wav audio/x-wav
ns_param .pdb chemical/x-pdb
ns_param .xyz chemical/x-xyz
ns_param .bmp image/bmp
ns_param .gif image/gif
ns_param .ief image/ief
ns_param .jpeg image/jpeg
ns_param .jpg image/jpeg
ns_param .png image/png
ns_param .tiff image/tiff
ns_param .wbmp image/vnd.wap.wbmp
ns_param .ras image/x-cmu-raster
ns_param .pnm image/x-portable-anymap
ns_param .pbm image/x-portable-bitmap
ns_param .pgm image/x-portable-graymap
ns_param .ppm image/x-portable-pixmap
ns_param .rgb image/x-rgb
ns_param .xbm image/x-xbitmap
ns_param .xpm image/x-xpixmap
ns_param .xwd image/x-xwindowdump
ns_param .igs model/iges
ns_param .msh model/mesh
ns_param .wrl model/vrml
ns_param .css text/css
ns_param .asc text/plain
ns_param .rtx text/richtext
ns_param .rtf text/rtf
ns_param .sgml text/sgml
ns_param .tsv text/tab-separated-values
ns_param .si text/vnd.wap.si
ns_param .sl text/vnd.wap.sl
ns_param .wml text/vnd.wap.wml
ns_param .wmls text/vnd.wap.wmlscript
ns_param .etx text/x-setext
ns_param .xml text/xml
ns_param .mpeg video/mpeg
ns_param .qt video/quicktime
ns_param .mxu video/vnd.mpegurl
ns_param .avi video/x-msvideo
ns_param .movie video/x-sgi-movie
ns_param .ice x-conference/x-cooltalk
ns_param .html text/html
ns_param .htm text/html
ns_param .ico image/x-icon
ns_param .eml message/rfc822
ns_param .mm application/x-freemind
ns_param .spec text/plain
ns_param .vcf text/x-vcard
